### PR TITLE
Provide custom function on word click

### PR DESCRIPTION
**Pull request by dotdestroyer**
This provides a way for a developer to specify their own custom handler for word click events, allowing for greater flexibility.

### CODE REVIEW

**Comment by wvengen** [comment]
Much better, thanks!

**Comment by wvengen** [comment]
One thing remaining: update the example :)

**Comment by dotdestroyer** [comment]
Done

**Comment by wvengen** [comment]
Thanks!

**Comment by wvengen** [comment]
Hmmm, I merged it, but there is one step back: now words _without_ a _href_ do also receive the 'click me' styling on mouseover :(

**Comment by dotdestroyer** [comment]
Sounds like the abstraction isn't quite right... I've got an idea, I'll propose a fix :)

**Comment by wvengen** [comment]
What was your idea?

**Pull request merged**
